// global
export const GLOBAL_INFO = "GLOBAL_INFO";
export const GLOBAL_SUCCESS = "GLOBAL_SUCCESS";
export const GLOBAL_WARING = "GLOBAL_WARING";
export const GLOBAL_ERROR = "GLOBAL_ERROR";
export const GLOBAL_NAV = "GLOBAL_NAV";

// index
export const INDEX_KEYWORD = "INDEX_KEYWORD";
export const INDEX_DATE = "INDEX_DATE";
export const INDEX_TABLE_LIST = "INDEX_TABLE_LIST";
export const INDEX_LOADING = "INDEX_LOADING";
export const INDEX_PAGINATION = "INDEX_PAGINATION";
export const INDEX_COLUMNS = "INDEX_COLUMNS";

// table detail
export const TABLE_DETAIL_DATABASE = "TABLE_DETAIL_DATABASE";
export const TABLE_DETAIL_TABLE = "TABLE_DETAIL_TABLE";
export const TABLE_DETAIL_STATUS_LIST = "TABLE_DETAIL_STATUS_LIST";
export const TABLE_DETAIL_LOADING = "TABLE_DETAIL_LOADING";
export const TABLE_DETAIL_PAGINATION = "TABLE_DETAIL_PAGINATION";
export const TABLE_DETAIL_COLUMN = "TABLE_DETAIL_COLUMN";
